@startuml
left to right direction
component "Presentation Layer" {
    component "Route"
    port "Presentation Port" as PresentationPort
    port "Application Access Port" as AppAccessPort
}

component "Application Layer" {

    port "JobService Port" as ServicePort
    component "JobService"
    ServicePort --> JobService
}

interface "Presentation API" as PresentationAPI
PresentationPort -left- PresentationAPI

note right of PresentationAPI
Takes: HTTP Request
Returns: HTTP Response
end note

interface "JobService API" as JobServiceAPI
ServicePort -right- JobServiceAPI
AppAccessPort --> JobServiceAPI: Command/ Query

note right of JobServiceAPI
Takes: Command/ Query
Returns: ApplicationResult
end note

component "Client"
[Client] --> PresentationAPI: HTTP Request
PresentationPort --> [Route]
[Route] --> AppAccessPort
PresentationAPI --> [Client]: HTTP Response
@enduml